export { ExampleButtons } from './examples/buttons'
export { Home } from './home'
export { NotFound } from './not-found'
export { Projects } from './projects'
export { GameMemory } from './puzzles/memory'
export { Puzzle } from './puzzles/puzzle'
export { TimeRecord } from './time-record'
